language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "vandersozc-github"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
jdk:
 - oraclejdk8

script:
 # JaCoCo is used to have code coverage, the agent has to be activated
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
 directories:
   - '$HOME/.m2/repository'
   - '$HOME/.sonar/cache'

notifications:
  email:
    - vando.zc@gmail.com