global:
  - CC_TEST_REPORTER_ID=$CODE_REPO
    
language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "vandersozc-github"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
after_script:
  - ./cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT