language: java

after_success:
  - "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
install:
  - "mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
jdk:
  - openjdk8

notifications:
  email:
    - vando.zc@gmail.com