language: java
sudo: false
install: true

jdk:
 - oraclejdk8

script:
 # JaCoCo is used to have code coverage, the agent has to be activated
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=vandersozc-github -Dsonar.login=691e13b9f90d41395897736e5d467145479b8229 -Dsonar.branch=master

cache:
 directories:
   - '$HOME/.m2/repository'
   - '$HOME/.sonar/cache'

notifications:
  email:
    - vando.zc@gmail.com